### ISSUE TITLE
Getting UnboundLocalError with train command

### ISSUE THREAD

**Issue by VwakeM** [marco-willi/camera-trap-classifier#20]
Hi Marco, 

I am getting following error with the train command: 

```
/usr/local/lib/python3.5/dist-packages/camera_trap_classifier/config/config.py:19: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.cfg = yaml.load(fp)
Traceback (most recent call last):
  File "/usr/local/bin/ctc.train", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/camera_trap_classifier/train.py", line 376, in main
    n_parallel_file_reads=args['n_parallel_file_reads'])
  File "/usr/local/lib/python3.5/dist-packages/camera_trap_classifier/data/utils.py", line 368, in n_records_in_tfr_dataset
    logger.debug("Finished -- Counted {} records".format(counter[-1]))
UnboundLocalError: local variable 'counter' referenced before assignment

```

My train command looks like this: 

`ctc.train -train_tfr_path $PWD/tfr_files -val_tfr_path $PWD/tfr_files -test_tfr_path $PWD/tfr_files -class_mapping_json $PWD/tfr_files/label_mapping.json -run_outputs_dir $PWD/my_model1_run1/ -model_save_dir $PWD/my_model1_save1/ -model ResNet18 -labels class -batch_size 128 -n_cpus 4 -buffer_size 512 -max_epochs 70`

Any thoughts as to what I might be doing wrong? Thanks as always!

**Comment by marco-willi** [comment]
Hi Vivek,

The only way for me to reproduce this error was when I used an invalid (empty) .tfrecord file. I suggest the following:

1. Verify that there are one or more files in `$PWD/tfr_files` with the following pattern `train_*.tfrecord` 
2. Inspect hat these files appear valid, e.g., have size > 0 KB.
3. Check the log-files of the code that created the tfrecord files to ensure it worked as expected.

Let me know if the problem persists.

**Comment by VwakeM** [comment]
Hi Marco, 

It was in fact a case of `train_*.tfrecord` being 0KB files. I have tracked down the issue and this is no longer a problem. Thanks for help with debugging!
