### ISSUE TITLE
Code for Windows

### ISSUE THREAD

**Issue by sazidabintaislam** [marco-willi/camera-trap-classifier#22]
I am working on Camera Trap Images. I have just started and trying to understand the codes. It would be great if I could get an idea or resources for windows.

**Comment by marco-willi** [comment]
From what I have read, it is difficult to train models on Windows. The reason for this is the need to employ a GPU to effectively train models. Therefore, if your goal is to train a model on your own dataset I would recommend using cloud computing ressources. If you are not familiar with how to use cloud computing ressources I suggest to follow this guidelines [Link](https://github.com/marco-willi/camera-trap-classifier/blob/master/docs/Docker_GPU.md) and/or ask someone with Linux/Unix experience.

However, if your goal is to apply trained models, Windows is perfectly fine. I recommend to:

1. Install the Anaconda distribution [Link](https://github.com/marco-willi/camera-trap-classifier/blob/master/README.md#anaconda-users)
2. Follow the guidelines to use trained models here: [Link](https://github.com/marco-willi/camera-trap-classifier/blob/master/docs/trained_models.md)
3. Follow the instructions here to apply the model: [Link](https://github.com/marco-willi/camera-trap-classifier/blob/master/README.md#5-model-use)

**Comment by sazidabintaislam** [comment]
I am doing a project where I will detect Frog from images. I have collected 200 images but those are not labeled. Can you suggest me a good data labeling tool.

**Comment by marco-willi** [comment]
I can't recommend a specific tool. There are many available and it depends a lot on what you feel comfortable with and what the output of these tools is. 

200 images does not sound like a lot if it is the total number of images (and not per species). If the goal is to detect the presence of a frog you may want to check out this pre-trained object detection model: [https://github.com/microsoft/CameraTraps](https://github.com/microsoft/CameraTraps)
